version: '3.4'

services:
  mongo:
    container_name: "my-mongodb"
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=teste
    - MONGO_INITDB_ROOT_PASSWORD=teste
    ports:
    - '27017:27017'		
  consul:
    container_name: "my-consul"
    image: consul
    ports:
    - '8500:8500'
    - '8600:8600'		
  rabbitmq3:
    container_name: "my-rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
    ports:
    # AMQP protocol port
    - '5673:5672'
    # HTTP management UI
    - '15673:15672'
  docker-from-awesomeshop-dotnet:
    image: docker-from-awesomeshop-dotnet
    build:
      context: .
      dockerfile: AwesomeShop.Services.Orders.Api/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Development 
    ports:
      - "5006:80"
      - "5007:443"
