version: '3.4'

services:
  docker-from-awesomeshop-dotnet:
    image: docker-from-awesomeshop-dotnet
    build:
      context: .
      dockerfile: AwesomeShop.Services.Orders.Api/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Development 
    ports:
      - "5006:80"
      - "5007:443"
